version: "3.3"

services:
  dcs:
    image: ghcr.io/woodlandscomputerscience/woodlands-checkpoint/wcp:latest
    container_name: wcp
    restart: always
    volumes:
      - ./.env:/app/.env:ro
      - ./students.json:/app/students.json:ro
      - ./guilds.json:/app/guilds.json

